basePath: /
definitions:
  api.EventTriggerMessage:
    properties:
      messageName:
        type: string
      processVariablesLocal:
        additionalProperties:
          properties:
            type:
              type: string
            value: {}
          type: object
        type: object
      resultEnabled:
        type: boolean
      tenantId:
        type: string
    type: object
  model.CamundaDeployment:
    properties:
      deploymentTime: {}
      id:
        type: string
      name:
        type: string
      source:
        type: string
      tenantId:
        type: string
    type: object
  model.DeploymentMessage:
    properties:
      diagram:
        $ref: '#/definitions/model.Diagram'
      id:
        type: string
      incident_handling:
        $ref: '#/definitions/model.IncidentHandling'
      name:
        type: string
      source:
        description: optional
        type: string
      user_id:
        type: string
    type: object
  model.Diagram:
    properties:
      svg:
        type: string
      xml_deployed:
        type: string
    type: object
  model.ExtendedDeployment:
    properties:
      definition_id:
        type: string
      deploymentTime: {}
      diagram:
        type: string
      error:
        type: string
      id:
        type: string
      name:
        type: string
      source:
        type: string
      tenantId:
        type: string
    type: object
  model.HistoricProcessInstance:
    properties:
      businessKey:
        type: string
      caseInstanceId:
        type: string
      deleteReason:
        type: string
      durationInMillis:
        type: number
      endTime:
        type: string
      id:
        type: string
      processDefinitionId:
        type: string
      processDefinitionKey:
        type: string
      processDefinitionName:
        type: string
      processDefinitionVersion:
        type: number
      startActivityId:
        type: string
      startTime:
        type: string
      startUserId:
        type: string
      state:
        type: string
      superCaseInstanceId:
        type: string
      superProcessInstanceId:
        type: string
      tenantId:
        type: string
    type: object
  model.IncidentHandling:
    properties:
      notify:
        type: boolean
      restart:
        type: boolean
      restart_is_valid_option:
        type: boolean
    type: object
  model.ProcessDefinition:
    properties:
      Version:
        type: integer
      category:
        type: string
      deploymentId:
        type: string
      description:
        type: string
      diagram:
        type: string
      historyTimeToLive:
        type: integer
      id:
        type: string
      key:
        type: string
      name:
        type: string
      resource:
        type: string
      suspended:
        type: boolean
      tenantId:
        type: string
      versionTag:
        type: string
    type: object
  model.ProcessInstance:
    properties:
      businessKey:
        type: string
      caseInstanceId:
        type: string
      definitionId:
        type: string
      ended:
        type: boolean
      id:
        type: string
      suspended:
        type: boolean
      tenantId:
        type: string
    type: object
  model.Variable:
    properties:
      type:
        type: string
      value: {}
      valueInfo: {}
    type: object
  model.VariableMap:
    additionalProperties:
      $ref: '#/definitions/model.Variable'
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Process-Engine-Wrapper
  version: "0.1"
paths:
  /process-deployments:
    put:
      description: deploy process, meant for internal use by the process-deployment
        service, only admins may access this endpoint
      parameters:
      - description: deployment
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/model.DeploymentMessage'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: deploy process
      tags:
      - deployment
  /process-deployments/{userid}/{deplid}:
    delete:
      description: delete deployment, meant for internal use by the process-deployment
        service, only admins may access this endpoint
      parameters:
      - description: deployment id
        in: path
        name: deplid
        required: true
        type: string
      - description: user id
        in: path
        name: userid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: delete deployment
      tags:
      - deployment
  /v2/deployments:
    get:
      description: list deployments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ExtendedDeployment'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: list deployments
      tags:
      - deployment
  /v2/deployments/{id}:
    get:
      description: get process deployment by id
      parameters:
      - description: deployment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CamundaDeployment'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get deployment
      tags:
      - deployment
  /v2/deployments/{id}/definition:
    get:
      description: get deployment process-definition
      parameters:
      - description: deployment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProcessDefinition'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get deployment process-definition
      tags:
      - deployment
      - process-definition
  /v2/deployments/{id}/exists:
    get:
      description: deployment exists
      parameters:
      - description: deployment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: deployment exists
      tags:
      - deployment
  /v2/deployments/{id}/instances:
    get:
      description: get deployment process-instances
      parameters:
      - description: deployment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ProcessInstance'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get deployment process-instances
      tags:
      - deployment
      - process-instance
  /v2/deployments/{id}/parameter:
    get:
      description: get deployment start parameter
      parameters:
      - description: deployment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.VariableMap'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get deployment parameter
      tags:
      - start
      - deployment
  /v2/deployments/{id}/start:
    get:
      description: start deployment by id
      parameters:
      - description: deployment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProcessInstance'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: start deployment
      tags:
      - start
      - deployment
  /v2/event-trigger:
    post:
      description: trigger event
      parameters:
      - description: ref https://docs.camunda.org/rest/camunda-bpm-platform/7.23-SNAPSHOT/#tag/Message/operation/deliverMessage
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/api.EventTriggerMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: trigger event
      tags:
      - event
  /v2/history/process-instances:
    get:
      description: list historic process-instances
      parameters:
      - description: if set to true, wraps the result in an objet with the result
          {total:0, data:[]}
        in: query
        name: with_total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.HistoricProcessInstance'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: list historic process-instances
      tags:
      - process-instance
  /v2/history/process-instances/{id}:
    delete:
      description: delete historic process-instance
      parameters:
      - description: process-instance id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: delete historic process-instance
      tags:
      - process-instance
  /v2/process-definitions/{id}:
    get:
      description: get process-definition
      parameters:
      - description: process-definition id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProcessDefinition'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get process-definition
      tags:
      - process-definition
  /v2/process-definitions/{id}/diagram:
    get:
      description: get process-definition diagram
      parameters:
      - description: process-definition id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get process-definition diagram
      tags:
      - process-definition
  /v2/process-definitions/{id}/start:
    get:
      description: start process-definitions by id
      parameters:
      - description: process-definitions id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: start process-definitions
      tags:
      - start
      - process-definitions
  /v2/process-definitions/{id}/start/id:
    get:
      description: start process-definitions and get started process-instance
      parameters:
      - description: process-definitions id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProcessInstance'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: start process-definitions and get instance
      tags:
      - start
      - process-definitions
  /v2/process-instances:
    delete:
      description: delete multiple historic process-instances
      parameters:
      - description: ids
        in: body
        name: message
        required: true
        schema:
          items:
            type: string
          type: array
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: delete multiple historic process-instances
      tags:
      - process-instance
    get:
      description: list process-instances
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ProcessInstance'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: list process-instances
      tags:
      - process-instance
  /v2/process-instances/{id}:
    delete:
      description: delete process-instance
      parameters:
      - description: process-instance id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: delete process-instance
      tags:
      - process-instance
  /v2/process-instances/{id}/variables/{variable_name}:
    put:
      description: set process-instance variable
      parameters:
      - description: process-instance id
        in: path
        name: id
        required: true
        type: string
      - description: variable_name
        in: path
        name: variable_name
        required: true
        type: string
      - description: value
        in: body
        name: message
        required: true
        schema: {}
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: set process-instance variable
      tags:
      - process-instance
  /v2/process-instances/count:
    get:
      description: process-instance count
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: process-instance count
      tags:
      - process-instance
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
